// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export class Listener extends pulumi.CustomResource {
    /**
     * Get an existing Listener resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ListenerState, opts?: pulumi.CustomResourceOptions): Listener {
        return new Listener(name, <any>state, { ...opts, id: id });
    }

    public readonly balancerId: pulumi.Output<string>;
    public readonly port: pulumi.Output<number>;
    public readonly protocol: pulumi.Output<string>;
    public readonly tags: pulumi.Output<{ key: string, value: string }[] | undefined>;
    public readonly tlsConfig: pulumi.Output<{ certificateIds: string[], cipherSuites: string[], maxVersion: string, minVersion: string, preferServerCipherSuites: boolean, sessionTicketsDisabled: boolean } | undefined>;

    /**
     * Create a Listener resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ListenerArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ListenerArgs | ListenerState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state: ListenerState = argsOrState as ListenerState | undefined;
            inputs["balancerId"] = state ? state.balancerId : undefined;
            inputs["port"] = state ? state.port : undefined;
            inputs["protocol"] = state ? state.protocol : undefined;
            inputs["tags"] = state ? state.tags : undefined;
            inputs["tlsConfig"] = state ? state.tlsConfig : undefined;
        } else {
            const args = argsOrState as ListenerArgs | undefined;
            if (!args || args.balancerId === undefined) {
                throw new Error("Missing required property 'balancerId'");
            }
            if (!args || args.port === undefined) {
                throw new Error("Missing required property 'port'");
            }
            if (!args || args.protocol === undefined) {
                throw new Error("Missing required property 'protocol'");
            }
            inputs["balancerId"] = args ? args.balancerId : undefined;
            inputs["port"] = args ? args.port : undefined;
            inputs["protocol"] = args ? args.protocol : undefined;
            inputs["tags"] = args ? args.tags : undefined;
            inputs["tlsConfig"] = args ? args.tlsConfig : undefined;
        }
        super("spotinst:multai/listener:Listener", name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Listener resources.
 */
export interface ListenerState {
    readonly balancerId?: pulumi.Input<string>;
    readonly port?: pulumi.Input<number>;
    readonly protocol?: pulumi.Input<string>;
    readonly tags?: pulumi.Input<pulumi.Input<{ key: pulumi.Input<string>, value: pulumi.Input<string> }>[]>;
    readonly tlsConfig?: pulumi.Input<{ certificateIds: pulumi.Input<pulumi.Input<string>[]>, cipherSuites: pulumi.Input<pulumi.Input<string>[]>, maxVersion: pulumi.Input<string>, minVersion: pulumi.Input<string>, preferServerCipherSuites: pulumi.Input<boolean>, sessionTicketsDisabled: pulumi.Input<boolean> }>;
}

/**
 * The set of arguments for constructing a Listener resource.
 */
export interface ListenerArgs {
    readonly balancerId: pulumi.Input<string>;
    readonly port: pulumi.Input<number>;
    readonly protocol: pulumi.Input<string>;
    readonly tags?: pulumi.Input<pulumi.Input<{ key: pulumi.Input<string>, value: pulumi.Input<string> }>[]>;
    readonly tlsConfig?: pulumi.Input<{ certificateIds: pulumi.Input<pulumi.Input<string>[]>, cipherSuites: pulumi.Input<pulumi.Input<string>[]>, maxVersion: pulumi.Input<string>, minVersion: pulumi.Input<string>, preferServerCipherSuites: pulumi.Input<boolean>, sessionTicketsDisabled: pulumi.Input<boolean> }>;
}
