// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export class Target extends pulumi.CustomResource {
    /**
     * Get an existing Target resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TargetState, opts?: pulumi.CustomResourceOptions): Target {
        return new Target(name, <any>state, { ...opts, id: id });
    }

    public readonly balancerId: pulumi.Output<string>;
    public readonly host: pulumi.Output<string>;
    public readonly name: pulumi.Output<string | undefined>;
    public readonly port: pulumi.Output<number | undefined>;
    public readonly tags: pulumi.Output<{ key: string, value: string }[] | undefined>;
    public readonly targetSetId: pulumi.Output<string>;
    public readonly weight: pulumi.Output<number>;

    /**
     * Create a Target resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TargetArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TargetArgs | TargetState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state: TargetState = argsOrState as TargetState | undefined;
            inputs["balancerId"] = state ? state.balancerId : undefined;
            inputs["host"] = state ? state.host : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["port"] = state ? state.port : undefined;
            inputs["tags"] = state ? state.tags : undefined;
            inputs["targetSetId"] = state ? state.targetSetId : undefined;
            inputs["weight"] = state ? state.weight : undefined;
        } else {
            const args = argsOrState as TargetArgs | undefined;
            if (!args || args.balancerId === undefined) {
                throw new Error("Missing required property 'balancerId'");
            }
            if (!args || args.host === undefined) {
                throw new Error("Missing required property 'host'");
            }
            if (!args || args.targetSetId === undefined) {
                throw new Error("Missing required property 'targetSetId'");
            }
            if (!args || args.weight === undefined) {
                throw new Error("Missing required property 'weight'");
            }
            inputs["balancerId"] = args ? args.balancerId : undefined;
            inputs["host"] = args ? args.host : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["port"] = args ? args.port : undefined;
            inputs["tags"] = args ? args.tags : undefined;
            inputs["targetSetId"] = args ? args.targetSetId : undefined;
            inputs["weight"] = args ? args.weight : undefined;
        }
        super("spotinst:multai/target:Target", name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Target resources.
 */
export interface TargetState {
    readonly balancerId?: pulumi.Input<string>;
    readonly host?: pulumi.Input<string>;
    readonly name?: pulumi.Input<string>;
    readonly port?: pulumi.Input<number>;
    readonly tags?: pulumi.Input<pulumi.Input<{ key: pulumi.Input<string>, value: pulumi.Input<string> }>[]>;
    readonly targetSetId?: pulumi.Input<string>;
    readonly weight?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a Target resource.
 */
export interface TargetArgs {
    readonly balancerId: pulumi.Input<string>;
    readonly host: pulumi.Input<string>;
    readonly name?: pulumi.Input<string>;
    readonly port?: pulumi.Input<number>;
    readonly tags?: pulumi.Input<pulumi.Input<{ key: pulumi.Input<string>, value: pulumi.Input<string> }>[]>;
    readonly targetSetId: pulumi.Input<string>;
    readonly weight: pulumi.Input<number>;
}
