// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package azure

import (
	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// Provides a Spotinst elastigroup Azure resource.
type Elastigroup struct {
	s *pulumi.ResourceState
}

// NewElastigroup registers a new resource with the given unique name, arguments, and options.
func NewElastigroup(ctx *pulumi.Context,
	name string, args *ElastigroupArgs, opts ...pulumi.ResourceOpt) (*Elastigroup, error) {
	if args == nil || args.LowPrioritySizes == nil {
		return nil, errors.New("missing required argument 'LowPrioritySizes'")
	}
	if args == nil || args.Name == nil {
		return nil, errors.New("missing required argument 'Name'")
	}
	if args == nil || args.Network == nil {
		return nil, errors.New("missing required argument 'Network'")
	}
	if args == nil || args.OdSizes == nil {
		return nil, errors.New("missing required argument 'OdSizes'")
	}
	if args == nil || args.Product == nil {
		return nil, errors.New("missing required argument 'Product'")
	}
	if args == nil || args.Region == nil {
		return nil, errors.New("missing required argument 'Region'")
	}
	if args == nil || args.ResourceGroupName == nil {
		return nil, errors.New("missing required argument 'ResourceGroupName'")
	}
	if args == nil || args.Strategy == nil {
		return nil, errors.New("missing required argument 'Strategy'")
	}
	inputs := make(map[string]interface{})
	if args == nil {
		inputs["desiredCapacity"] = nil
		inputs["healthCheck"] = nil
		inputs["images"] = nil
		inputs["loadBalancers"] = nil
		inputs["login"] = nil
		inputs["lowPrioritySizes"] = nil
		inputs["maxSize"] = nil
		inputs["minSize"] = nil
		inputs["name"] = nil
		inputs["network"] = nil
		inputs["odSizes"] = nil
		inputs["product"] = nil
		inputs["region"] = nil
		inputs["resourceGroupName"] = nil
		inputs["scheduledTasks"] = nil
		inputs["strategy"] = nil
		inputs["userData"] = nil
	} else {
		inputs["desiredCapacity"] = args.DesiredCapacity
		inputs["healthCheck"] = args.HealthCheck
		inputs["images"] = args.Images
		inputs["loadBalancers"] = args.LoadBalancers
		inputs["login"] = args.Login
		inputs["lowPrioritySizes"] = args.LowPrioritySizes
		inputs["maxSize"] = args.MaxSize
		inputs["minSize"] = args.MinSize
		inputs["name"] = args.Name
		inputs["network"] = args.Network
		inputs["odSizes"] = args.OdSizes
		inputs["product"] = args.Product
		inputs["region"] = args.Region
		inputs["resourceGroupName"] = args.ResourceGroupName
		inputs["scheduledTasks"] = args.ScheduledTasks
		inputs["strategy"] = args.Strategy
		inputs["userData"] = args.UserData
	}
	s, err := ctx.RegisterResource("spotinst:azure/elastigroup:Elastigroup", name, true, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &Elastigroup{s: s}, nil
}

// GetElastigroup gets an existing Elastigroup resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetElastigroup(ctx *pulumi.Context,
	name string, id pulumi.ID, state *ElastigroupState, opts ...pulumi.ResourceOpt) (*Elastigroup, error) {
	inputs := make(map[string]interface{})
	if state != nil {
		inputs["desiredCapacity"] = state.DesiredCapacity
		inputs["healthCheck"] = state.HealthCheck
		inputs["images"] = state.Images
		inputs["loadBalancers"] = state.LoadBalancers
		inputs["login"] = state.Login
		inputs["lowPrioritySizes"] = state.LowPrioritySizes
		inputs["maxSize"] = state.MaxSize
		inputs["minSize"] = state.MinSize
		inputs["name"] = state.Name
		inputs["network"] = state.Network
		inputs["odSizes"] = state.OdSizes
		inputs["product"] = state.Product
		inputs["region"] = state.Region
		inputs["resourceGroupName"] = state.ResourceGroupName
		inputs["scheduledTasks"] = state.ScheduledTasks
		inputs["strategy"] = state.Strategy
		inputs["userData"] = state.UserData
	}
	s, err := ctx.ReadResource("spotinst:azure/elastigroup:Elastigroup", name, id, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &Elastigroup{s: s}, nil
}

// URN is this resource's unique name assigned by Pulumi.
func (r *Elastigroup) URN() *pulumi.URNOutput {
	return r.s.URN()
}

// ID is this resource's unique identifier assigned by its provider.
func (r *Elastigroup) ID() *pulumi.IDOutput {
	return r.s.ID()
}

// The desired number of instances the group should have at any time.
func (r *Elastigroup) DesiredCapacity() *pulumi.IntOutput {
	return (*pulumi.IntOutput)(r.s.State["desiredCapacity"])
}

// Describes the health check configuration.
func (r *Elastigroup) HealthCheck() *pulumi.Output {
	return r.s.State["healthCheck"]
}

// Image of a VM. An image is a template for creating new VMs. Choose from Azure image catalogue (marketplace) or use a custom image.
func (r *Elastigroup) Images() *pulumi.ArrayOutput {
	return (*pulumi.ArrayOutput)(r.s.State["images"])
}

// Describes a set of one or more classic load balancer target groups and/or Multai load balancer target sets.
func (r *Elastigroup) LoadBalancers() *pulumi.ArrayOutput {
	return (*pulumi.ArrayOutput)(r.s.State["loadBalancers"])
}

// Describes the login configuration.
func (r *Elastigroup) Login() *pulumi.Output {
	return r.s.State["login"]
}

// Available Low-Priority sizes.
func (r *Elastigroup) LowPrioritySizes() *pulumi.ArrayOutput {
	return (*pulumi.ArrayOutput)(r.s.State["lowPrioritySizes"])
}

// The maximum number of instances the group should have at any time.
func (r *Elastigroup) MaxSize() *pulumi.IntOutput {
	return (*pulumi.IntOutput)(r.s.State["maxSize"])
}

// The minimum number of instances the group should have at any time.
func (r *Elastigroup) MinSize() *pulumi.IntOutput {
	return (*pulumi.IntOutput)(r.s.State["minSize"])
}

// The group name.
func (r *Elastigroup) Name() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["name"])
}

// Defines the Virtual Network and Subnet for your Elastigroup.
func (r *Elastigroup) Network() *pulumi.Output {
	return r.s.State["network"]
}

// Available On-Demand sizes
func (r *Elastigroup) OdSizes() *pulumi.ArrayOutput {
	return (*pulumi.ArrayOutput)(r.s.State["odSizes"])
}

// Operation system type. Valid values: `"Linux"`, `"Windows"`.
func (r *Elastigroup) Product() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["product"])
}

// The region your Azure group will be created in.
func (r *Elastigroup) Region() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["region"])
}

// Vnet Resource Group Name.
func (r *Elastigroup) ResourceGroupName() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["resourceGroupName"])
}

// Describes the configuration of one or more scheduled tasks.
func (r *Elastigroup) ScheduledTasks() *pulumi.ArrayOutput {
	return (*pulumi.ArrayOutput)(r.s.State["scheduledTasks"])
}

// Describes the deployment strategy.
func (r *Elastigroup) Strategy() *pulumi.Output {
	return r.s.State["strategy"]
}

// Base64-encoded MIME user data to make available to the instances.
func (r *Elastigroup) UserData() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["userData"])
}

// Input properties used for looking up and filtering Elastigroup resources.
type ElastigroupState struct {
	// The desired number of instances the group should have at any time.
	DesiredCapacity interface{}
	// Describes the health check configuration.
	HealthCheck interface{}
	// Image of a VM. An image is a template for creating new VMs. Choose from Azure image catalogue (marketplace) or use a custom image.
	Images interface{}
	// Describes a set of one or more classic load balancer target groups and/or Multai load balancer target sets.
	LoadBalancers interface{}
	// Describes the login configuration.
	Login interface{}
	// Available Low-Priority sizes.
	LowPrioritySizes interface{}
	// The maximum number of instances the group should have at any time.
	MaxSize interface{}
	// The minimum number of instances the group should have at any time.
	MinSize interface{}
	// The group name.
	Name interface{}
	// Defines the Virtual Network and Subnet for your Elastigroup.
	Network interface{}
	// Available On-Demand sizes
	OdSizes interface{}
	// Operation system type. Valid values: `"Linux"`, `"Windows"`.
	Product interface{}
	// The region your Azure group will be created in.
	Region interface{}
	// Vnet Resource Group Name.
	ResourceGroupName interface{}
	// Describes the configuration of one or more scheduled tasks.
	ScheduledTasks interface{}
	// Describes the deployment strategy.
	Strategy interface{}
	// Base64-encoded MIME user data to make available to the instances.
	UserData interface{}
}

// The set of arguments for constructing a Elastigroup resource.
type ElastigroupArgs struct {
	// The desired number of instances the group should have at any time.
	DesiredCapacity interface{}
	// Describes the health check configuration.
	HealthCheck interface{}
	// Image of a VM. An image is a template for creating new VMs. Choose from Azure image catalogue (marketplace) or use a custom image.
	Images interface{}
	// Describes a set of one or more classic load balancer target groups and/or Multai load balancer target sets.
	LoadBalancers interface{}
	// Describes the login configuration.
	Login interface{}
	// Available Low-Priority sizes.
	LowPrioritySizes interface{}
	// The maximum number of instances the group should have at any time.
	MaxSize interface{}
	// The minimum number of instances the group should have at any time.
	MinSize interface{}
	// The group name.
	Name interface{}
	// Defines the Virtual Network and Subnet for your Elastigroup.
	Network interface{}
	// Available On-Demand sizes
	OdSizes interface{}
	// Operation system type. Valid values: `"Linux"`, `"Windows"`.
	Product interface{}
	// The region your Azure group will be created in.
	Region interface{}
	// Vnet Resource Group Name.
	ResourceGroupName interface{}
	// Describes the configuration of one or more scheduled tasks.
	ScheduledTasks interface{}
	// Describes the deployment strategy.
	Strategy interface{}
	// Base64-encoded MIME user data to make available to the instances.
	UserData interface{}
}
